<?php
include('../app/func/echoCard.php');
include('../app/func/echoGrid.php');
include('../app/func/callApi.php');
include('../app/func/sortBy.php');
include('../app/func/addBrand.php');
include('../app/func/addSize.php');
include('../app/func/addProduct.php');
include('../app/func/uploadImage.php');
